
#ifndef ds_vm_h
#define ds_vm_h

#include <stdint.h>
#include <string.h>

#include "input_task.h"
#include "dsb_cache.h"

#define BUF_PADDING 8
#define EXE_BIN_START_ADDRESS 0x0
#define EXE_BIN_END_ADDRESS_INCLUSIVE 0xDFFF
#define STACK_BASE_ADDR 0xEFFF
#define STACK_BUF_SIZE 512
#define BIN_BUF_SIZE 512

#define USER_VAR_START_ADDRESS 0xF000
#define USER_VAR_END_ADDRESS_INCLUSIVE 0xF0FF
#define USER_VAR_BUF_SIZE (USER_VAR_END_ADDRESS_INCLUSIVE - USER_VAR_START_ADDRESS + BUF_PADDING)

#define SCRATCH_MEM_START_ADDRESS 0xF400
#define SCRATCH_MEM_END_ADDRESS_INCLUSIVE 0xF4FF
#define SCRATCH_MEM_BUF_SIZE (SCRATCH_MEM_END_ADDRESS_INCLUSIVE - SCRATCH_MEM_START_ADDRESS + BUF_PADDING)

#define PGV_START_ADDRESS 0xFC00
#define PGV_COUNT 32
#define PGV_BYTE_WIDTH 4
#define PGV_END_ADDRESS_INCLUSIVE 0xFC7F
#define PGV_BUF_SIZE (PGV_END_ADDRESS_INCLUSIVE - PGV_START_ADDRESS + BUF_PADDING)

#define INTERAL_VAR_START_ADDRESS 0xFE00
#define INTERAL_VAR_BYTE_WIDTH 4
#define INTERAL_VAR_END_ADDRESS_INCLUSIVE 0xFE7F

#define MEM_END_ADDR 0xFFFF

#define MAX_INSTRUCTION_LEN 5
#define HIDTX_PACKET_SIZE 9

#define EXE_OK 0

#define EXE_ACTION_SLEEP 1
#define EXE_ACTION_PREV_PROFILE 2
#define EXE_ACTION_NEXT_PROFILE 3
#define EXE_ACTION_GOTO_PROFILE 4

#define EXE_HALT 10
#define EXE_ABORTED 11

#define EXE_ERROR_CODE_START 20
#define EXE_ILLEGAL_INSTRUCTION (EXE_ERROR_CODE_START + 0)
#define EXE_DSB_INCOMPATIBLE_VERSION (EXE_ERROR_CODE_START + 1)
#define EXE_DSB_FOPEN_FAIL (EXE_ERROR_CODE_START + 2)
#define EXE_DSB_FREAD_ERROR (EXE_ERROR_CODE_START + 3)
#define EXE_STACK_OVERFLOW (EXE_ERROR_CODE_START + 4)
#define EXE_STACK_UNDERFLOW (EXE_ERROR_CODE_START + 5)
#define EXE_DIVISION_BY_ZERO (EXE_ERROR_CODE_START + 6)
#define EXE_ILLEGAL_ADDR (EXE_ERROR_CODE_START + 7)
#define EXE_DSB_FILE_TOO_LARGE (EXE_ERROR_CODE_START + 8)
#define EXE_UNIMPLEMENTED (EXE_ERROR_CODE_START + 9)
#define EXE_UNALIGNED_ACCESS (EXE_ERROR_CODE_START + 10)
#define EXE_PROFILE_NOT_FOUND (EXE_ERROR_CODE_START + 11)
#define EXE_STR_ERROR (EXE_ERROR_CODE_START + 12)

#define _DEFAULTDELAY (INTERAL_VAR_START_ADDRESS + 0 * INTERAL_VAR_BYTE_WIDTH)
#define _DEFAULTCHARDELAY (INTERAL_VAR_START_ADDRESS + 1 * INTERAL_VAR_BYTE_WIDTH)
#define _CHARJITTER (INTERAL_VAR_START_ADDRESS + 2 * INTERAL_VAR_BYTE_WIDTH)
#define _RANDOM_MIN (INTERAL_VAR_START_ADDRESS + 3 * INTERAL_VAR_BYTE_WIDTH)
#define _RANDOM_MAX (INTERAL_VAR_START_ADDRESS + 4 * INTERAL_VAR_BYTE_WIDTH)
#define _RANDOM_INT (INTERAL_VAR_START_ADDRESS + 5 * INTERAL_VAR_BYTE_WIDTH)
#define _TIME_MS (INTERAL_VAR_START_ADDRESS + 6 * INTERAL_VAR_BYTE_WIDTH)
#define _READKEY (INTERAL_VAR_START_ADDRESS + 7 * INTERAL_VAR_BYTE_WIDTH)
#define _LOOP_SIZE (INTERAL_VAR_START_ADDRESS + 8 * INTERAL_VAR_BYTE_WIDTH)
#define _KEYPRESS_COUNT (INTERAL_VAR_START_ADDRESS + 9 * INTERAL_VAR_BYTE_WIDTH)
#define _EPILOGUE_ACTIONS (INTERAL_VAR_START_ADDRESS + 10 * INTERAL_VAR_BYTE_WIDTH)
#define _TIME_S (INTERAL_VAR_START_ADDRESS + 11 * INTERAL_VAR_BYTE_WIDTH)
#define _ALLOW_ABORT (INTERAL_VAR_START_ADDRESS + 12 * INTERAL_VAR_BYTE_WIDTH)
#define _BLOCKING_READKEY (INTERAL_VAR_START_ADDRESS + 13 * INTERAL_VAR_BYTE_WIDTH)
#define _KBLED_BITFIELD (INTERAL_VAR_START_ADDRESS + 14 * INTERAL_VAR_BYTE_WIDTH)
#define _DONT_REPEAT (INTERAL_VAR_START_ADDRESS + 15 * INTERAL_VAR_BYTE_WIDTH)
#define _THIS_KEYID (INTERAL_VAR_START_ADDRESS + 16 * INTERAL_VAR_BYTE_WIDTH)
#define _DP_MODEL (INTERAL_VAR_START_ADDRESS + 17 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_IS_VALID (INTERAL_VAR_START_ADDRESS + 18 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_UTC_OFFSET (INTERAL_VAR_START_ADDRESS + 19 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_YEAR (INTERAL_VAR_START_ADDRESS + 20 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_MONTH (INTERAL_VAR_START_ADDRESS + 21 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_DAY (INTERAL_VAR_START_ADDRESS + 22 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_HOUR (INTERAL_VAR_START_ADDRESS + 23 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_MINUTE (INTERAL_VAR_START_ADDRESS + 24 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_SECOND (INTERAL_VAR_START_ADDRESS + 25 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_WDAY (INTERAL_VAR_START_ADDRESS + 26 * INTERAL_VAR_BYTE_WIDTH)
#define _RTC_YDAY (INTERAL_VAR_START_ADDRESS + 27 * INTERAL_VAR_BYTE_WIDTH)
#define _SW_BITFIELD (INTERAL_VAR_START_ADDRESS + 28 * INTERAL_VAR_BYTE_WIDTH)
#define _UNUSED MEM_END_ADDR

#define DUMMY_DATA_REPLACE_ME 69

typedef struct
{
  uint8_t result;
  uint16_t this_pc;
  uint16_t next_pc;
  uint8_t data;
  uint8_t epilogue_actions;
} exe_context;

#define DEFAULT_NONCHAR_DELAY_MS 20
#define DEFAULT_CHAR_DELAY_MS 20

#define EPILOGUE_SAVE_LOOP_STATE 0x1
#define EPILOGUE_SAVE_COLOR_STATE 0x2
#define EPILOGUE_NEED_OLED_RESTORE 0x4
#define EPILOGUE_DONT_AUTO_REPEAT 0x8
#define EPILOGUE_SAVE_PGV 0x10

#define MYMAX(a, b) ((a) > (b) ? (a) : (b))

extern uint8_t bin_buf[BIN_BUF_SIZE] __attribute__((aligned(4)));
extern uint8_t allow_abort;
extern uint8_t kb_led_status;
extern uint8_t pgv_buf[PGV_BUF_SIZE] __attribute__((aligned(4)));

#define MAKESTR_VAR_BOUNDARY_IMM (0x1f)
#define MAKESTR_VAR_BOUNDARY_REL (0x1e)

/*
  Stack grows from larger address to smaller address
  SP points to next available slot
*/
typedef struct
{
  uint16_t sp;         // Virtual Stack Pointer
  uint16_t fp;         // Virtual Frame Pointer
  uint16_t lower_bound;// Lowest allowed virtual address (Stack Limit)
  uint16_t upper_bound;// Highest allowed virtual address (Stack Base)
  uint8_t* ram_base;   // Host buffer backing the VM stack
} my_stack;

typedef uint32_t (*FUNC_PTR_BINOP)(uint32_t, uint32_t);
typedef uint32_t (*FUNC_PTR_UNARY)(uint32_t);

#define DS_SET_BITS(variable, mask)   ((variable) |= (mask))
#define DS_CLEAR_BITS(variable, mask) ((variable) &= ~(mask))

void run_dsb(exe_context* ctx, uint8_t this_key_id, char* dsb_path, uint8_t* dsb_cache_buf);
uint32_t my_randu32(void);
uint32_t random_uint32_between(uint32_t lower, uint32_t upper);
int32_t random_int32_between(int32_t lower, int32_t upper);
void switch_bank(uint16_t addr);
void read_binexe_bytes_safe(uint32_t vm_addr, void* dest, size_t size);

#define READ_BUF_SIZE (256 * 2)
extern char read_buffer[READ_BUF_SIZE];

#endif

